name: 'Cache on self- hosted runner'
description: 'Provide a description here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'archive'
  color: 'red'

# Define your inputs here.
inputs:
  path:
    description: 'A directory to save and restore cache.'
    required: true
  key:
    description: 'An explicit key for a cache.'
    required: true
  base:
    description: 'A base directory to save and restore cache.'
    required: false
    default: '/home/runner/.cache/gh-cache'

# Define your outputs here.
outputs:
  hit:
    description: 'Cache hit or not'

runs:
  using: node20
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
