name: 'Save a cache'
description: 'Save Cache artifacts like dependencies and build outputs to improve workflow execution time'
author: 'GitHub'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save caches that can be restored on other platforms'
    default: 'false'
    required: false
  use-local-cache:
    description: 'Use a local cache for saving and restoring cache'
    default: 'false'
    required: false
  base-directory:
    description: 'A base directory to save and restore cache.'
    required: false
    default: '/home/runner/.cache/gh-cache'
runs:
  using: 'node20'
  main: '../dist/save-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
